name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World!"
            echo "First Output"
            echo "Second Output"
            echo "Finally Github is in Action!"
      - name: Print goodbye
        run: echo "Done - bye"
